# written by: Ioannis Paraskevakos
# tested by: Ioannis Paraskevakos
# debugged by: Ioannis Paraskevakos
StateHash=[{"_id" : "NJ","name" : "New Jersey"}, 
{"_id" : "NY","name" : "New York"}, 
{"_id" : "AL","name" : "Alabama"}, 
{"_id" : "AK","name" : "Alaska"}, 
{"_id" : "AZ","name" : "Arizona"}, 
{"_id" : "AR","name" : "Arkansas"}, 
{"_id" : "CA","name" : "California"}, 
{"_id" : "CO","name" : "Colorado"}, 
{"_id" : "CT","name" : "Connecticut"}, 
{"_id" : "DE","name" : "Delaware"}, 
{"_id" : "FL","name" : "Florida"}, 
{"_id" : "GA","name" : "Georgia"}, 
{"_id" : "HI","name" : "Hawaii"}, 
{"_id" : "ID","name" : "Idaho"}, 
{"_id" : "NH","name" : "New Hampshire"}, 
{"_id" : "NM","name" : "New Mexico"}, 
{"_id" : "NC","name" : "North Carolina"}, 
{"_id" : "ND","name" : "North Dakota"}, 
{"_id" : "OH","name" : "Ohio"}, 
{"_id" : "OK","name" : "Oklahoma"}, 
{"_id" : "OR","name" : "Oregon"}, 
{"_id" : "PA","name" : "Pennsylvania"}, 
{"_id" : "RI","name" : "Rhode Island"}, 
{"_id" : "SC","name" : "South Carolina"}, 
{"_id" : "SD","name" : "South Dakota"}, 
{"_id" : "TN","name" : "Tennessee"}, 
{"_id" : "TX","name" : "Texas"}, 
{"_id" : "UT","name" : "Utah"}, 
{"_id" : "IL","name" : "Illinois"}, 
{"_id" : "IN","name" : "Indiana"}, 
{"_id" : "IA","name" : "Iowa"}, 
{"_id" : "KS","name" : "Kansas"}, 
{"_id" : "KY","name" : "Kentucky"}, 
{"_id" : "LA","name" : "Louisiana"}, 
{"_id" : "ME","name" : "Maine"}, 
{"_id" : "MD","name" : "Maryland"}, 
{"_id" : "MA","name" : "Massachusetts"}, 
{"_id" : "MI","name" : "Michigan"}, 
{"_id" : "MN","name" : "Minnesota"}, 
{"_id" : "MS","name" : "Mississippi"}, 
{"_id" : "MO","name" : "Missouri"}, 
{"_id" : "MT","name" : "Montana"}, 
{"_id" : "NE","name" : "Nebraska"}, 
{"_id" : "NV","name" : "Nevada"}, 
{"_id" : "VT","name" : "Vermont"}, 
{"_id" : "VA","name" : "Virginia"}, 
{"_id" : "WA","name" : "Washington"}, 
{"_id" : "WV","name" : "West Virginia"}, 
{"_id" : "WI","name" : "Wisconsin"}, 
{"_id" : "WY","name" : "Wyoming"}]
